### ISSUE TITLE
Is this library alive and maintIable?

### ISSUE THREAD

**Issue by lectricas** [warting/permissions-ui#378]
@warting 
Hi! Nice lib you have. Is this project neglected or I can rely on it?
Just checking.
Hope you answer asap. Sorry to messed up your issues here.

**Comment by warting** [comment]
Hi, I'm using it myself in various apps and maintaining it due to lack of official simple APIs for requesting background location permissions.

**Comment by lectricas** [comment]
Thanks!

**Comment by lectricas** [comment]
So, I found the culprit of the but. 

Adding this to manifest 

<provider
            android:name="androidx.startup.InitializationProvider"
            android:authorities="${applicationId}.androidx-startup"
            tools:node="remove" />

@warting Any ideas how to fix this?
