### ISSUE TITLE
How to use with Java

### ISSUE THREAD

**Issue by tscislo** [warting/permissions-ui#68]
I really like this UI for location permissions. Do you have any example on how to use it with Java?

**Comment by warting** [comment]
How would you like to use it with java? Do you use compose?

**Comment by warting** [comment]
How would you like to use it with java? Do you use compose?

**Comment by tscislo** [comment]
I'm not using compose. I don't know if this is even possible to use your activity (in Kotilin) in Java Android project

**Comment by warting** [comment]
How about if I made an activity that can be launched with a result? Is it specifically background location permission that you are interested in?

**Comment by tscislo** [comment]
I think I will go with my own activity with simillar logic to yours, but written in Java. Thanks for your help anyways!
