### ISSUE TITLE
Non-composable Android apps

### ISSUE THREAD

**Issue by juaparser** [warting/permissions-ui#78]
Can i use this library with an Android App that doesn't use compose? The implementation with gradle works fine, but when i tried to call the method in my OnViewCreated of a Fragment, I get conflicts, so I assume this library only works for Compose Apps?

Thanks!

**Comment by warting** [comment]
Let's make it work! How would you like to integrate it in your app?

**Comment by warting** [comment]
@juaparser It is possible today by using PermissionsUiContracts.RequestBackgroundLocation. I have added a sample app made with java and without compose. https://github.com/warting/permissions-ui/pull/81

Let me know if you would like to use it in some other way.
